spring:
  datasource:
    url: jdbc:mysql://localhost:3306/company?useSSL=false&serverTimezone=Europe/Warsaw
    driver-class-name: com.mysql.cj.jdbc.Driver #zaleznosc do MySql
    username: root
    password: password
  jpa:
    show-sql: true #pokazuje zapytania sql w konsoli
  sql:
    init:
      mode: always #Dla baz niewbudowanych zawarto?? pliku schema.sql domy?lnie nie jest wykonywana, dlatego nale?y w pliku application.yml doda? w?asno?? spring.sql.init.mode ustawion? na always.